resolver: lts-15.2

packages:
- .

extra-deps:
- clash-ghc-1.2.0
- clash-lib-1.2.0
- clash-prelude-1.2.0
- ghc-typelits-natnormalise-0.7.2
- ghc-typelits-extra-0.4
- type-errors-0.2.0.0
- first-class-families-0.5.0.0
- concurrent-supply-0.1.8

allow-newer: true